version: '3.8'
services:
    postgres:
        image: 'registry.cn-hangzhou.aliyuncs.com/redgreat/workgfs:latest'
        container_name: workgfs
        hostname: workgfs
        restart: unless-stopped
        volumes:
            - ./conf/:/app/conf
            - ./logs/:/app/logs
        environment:
            DISABLE_IPV6: 'true'
            TZ: 'Asia/Shanghai'
            LANG: 'zh_CN.UTF-8'
        deploy:
            resources:
                limits:
                    memory: 2G
                reservations:
                    memory: 128M
        mem_swappiness: 0
        oom_kill_disable: true
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
