CREATE TABLE `tb_workpriceedit_log` (
  `Id` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '主键（OF）',
  `WorkOrderId` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '工单Id（WI）',
  `AppCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工单申请编号',
  `ArtificialServicePriceId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '人工服务商品Id',
  `ArtificialServicePriceName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '人工服务商品名称',
  `ArtificialServicePriceAmount` int(8) DEFAULT NULL COMMENT '人工服务商品数量',
  `OrderTypeName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工单类型名称',
  `OrderType` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工单类型',
  `CustomerName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户名称',
  `Status` smallint(1) DEFAULT NULL COMMENT '1成功0失败',
  `OldPrice` decimal(10,2) DEFAULT NULL COMMENT '原价格',
  `InternalPrice` decimal(10,2) DEFAULT NULL COMMENT '内部结算总价（元）',
  `Reason` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '调价原因',
  `Remark` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注',
  `OperName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '操作人姓名',
  `OperCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '操作人Code',
  `OperTime` datetime DEFAULT NULL COMMENT '操作时间',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime DEFAULT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  KEY `NON-AppCode` (`AppCode`),
  KEY `NON-ArtificialServicePriceId` (`ArtificialServicePriceId`),
  KEY `NON-ArtificialServicePriceName` (`ArtificialServicePriceName`),
  KEY `NON-CustomerName` (`CustomerName`),
  KEY `NON-OperCode` (`OperCode`),
  KEY `NON-OperName` (`OperName`),
  KEY `NON-OrderType` (`OrderType`),
  KEY `NON-OrderTypeName` (`OrderTypeName`),
  KEY `NON-Status` (`Status`),
  KEY `NON-WorkOrderId` (`WorkOrderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='按单调价日志表';

CREATE TABLE `tb_feeapplicationinfo` (
  `Id` char(12) NOT NULL COMMENT '费用申请信息主键(FE)',
  `TargetId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `OrgCode` varchar(50) DEFAULT NULL COMMENT '组织编码（1001车电 1002金融 1003车务 1000平台）',
  `FeeGroupCode` varchar(50) DEFAULT NULL COMMENT '费用标准组Code',
  `AuditStatus` smallint(6) DEFAULT NULL COMMENT '审核状态（0已撤回 1待审核 2审核通过 3审核拒绝）',
  `FeeItemId` varchar(12) DEFAULT NULL COMMENT '费用配置项主键(tb_feeiteminfo.Id)',
  `FeeValue` decimal(16,2) DEFAULT NULL COMMENT '费用值',
  `ApplyFee` decimal(16,2) DEFAULT NULL COMMENT '申请金额',
  `FeeApplyTime` datetime DEFAULT NULL COMMENT '费用申请时间',
  `ApplyWorkStatus` int(11) DEFAULT NULL COMMENT '申请时工单状态',
  `SubsidyStatus` smallint(6) DEFAULT NULL COMMENT '发放状态(0未发放 1已发放）',
  `SubsidyTime` datetime DEFAULT NULL COMMENT '发放时间',
  `SubsidyRemark` varchar(200) DEFAULT NULL COMMENT '发放备注',
  `SubsidyLoginName` varchar(50) DEFAULT NULL COMMENT '发放人账号',
  `SubsidyName` varchar(100) DEFAULT NULL COMMENT '发放人姓名',
  `ApplyPersonCode` varchar(50) DEFAULT NULL COMMENT '申请人Code',
  `ApplyPersonName` varchar(100) DEFAULT NULL COMMENT '申请人姓名',
  `ApplyReason` varchar(300) DEFAULT NULL COMMENT '申请原因',
  `PayeeCode` varchar(50) DEFAULT NULL COMMENT '收款人工号',
  `PayeeName` varchar(100) DEFAULT NULL COMMENT '收款人姓名',
  `OriginalPayeeCode` varchar(50) DEFAULT NULL COMMENT '收款人工号(原)',
  `OriginalPayeeName` varchar(100) DEFAULT NULL COMMENT '收款人姓名(原)',
  `LastAuditPersonCode` varchar(50) DEFAULT NULL COMMENT '审核人Code(最新)',
  `LastAuditPersonName` varchar(100) DEFAULT NULL COMMENT '审核人姓名(最新)',
  `LastAuditTime` datetime DEFAULT NULL COMMENT '最新审核时间',
  `AuditRemark` varchar(200) DEFAULT NULL COMMENT '审核备注',
  `RuleActionLogId` varchar(12) DEFAULT NULL COMMENT '规则操作日志ID(common_ruleactionlog.Id)',
  `ExtraJson` json DEFAULT NULL COMMENT '费用额外信息(AccommodationTime住宿时间 CalculationMethod计算方式 SettleMethod人员自定义属性-服务商结算方式（CHP））',
  `DynamicFormJson` json DEFAULT NULL COMMENT '动态表单内容json',
  `v_SettleMethod` varchar(10) GENERATED ALWAYS AS (json_unquote(json_extract(`ExtraJson`,_utf8mb4'$.SettleMethod'))) VIRTUAL COMMENT '人员自定义属性-服务商结算方式（CHP）',
  `InsertTime` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-TargetId` (`TargetId`) USING BTREE,
  KEY `NON-OrgCode` (`OrgCode`) USING BTREE,
  KEY `NON-FeeItemId` (`FeeItemId`) USING BTREE,
  KEY `NON-FeeApplyTime` (`FeeApplyTime`) USING BTREE,
  KEY `NON-ApplyPersonCode` (`ApplyPersonCode`),
  KEY `NON-PayeeCode` (`PayeeCode`) USING BTREE,
  KEY `NON-LastAuditPersonCode` (`LastAuditPersonCode`) USING BTREE,
  KEY `NON-LastAuditTime` (`LastAuditTime`) USING BTREE,
  KEY `NON-SubsidyStatus` (`SubsidyStatus`) USING BTREE,
  KEY `NON-AuditStatus` (`AuditStatus`) USING BTREE,
  KEY `NON-RuleActionLogId` (`RuleActionLogId`) USING BTREE,
  KEY `SubsidyTime` (`SubsidyTime` DESC),
  KEY `FeeGroupCode` (`FeeGroupCode`),
  KEY `SettleMethod` (`v_SettleMethod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通用域_费用申请明细表';


CREATE TABLE `tb_workorderinfo` (
  `Id` varchar(36) NOT NULL COMMENT '工单主单主键(WI)',
  `AppCode` varchar(50) DEFAULT NULL COMMENT '工单申请编码',
  `SourceType` smallint(6) DEFAULT NULL COMMENT '工单来源(0工单下单1智车品2客户接口3LCRM下单4OCRM下单5平安私有云6金融SAAS推送7车务推送)',
  `OrderType` varchar(50) DEFAULT NULL COMMENT '工单类型Code(sys_ordertypeinfo.TypeCode)',
  `CreateType` smallint(6) DEFAULT NULL COMMENT '工单建单方式(来源二级分类)(1批量导入 2-APP 3-PC 4外部接口 5虚拟数据)',
  `ServiceProviderCode` varchar(50) DEFAULT NULL COMMENT '服务商Code(basic_serviceprovider.ProviderCode)',
  `WorkStatus` smallint(6) DEFAULT NULL COMMENT '工单状态(basic_workflowstatus.WorkStatus)',
  `CustomerId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户Id',
  `CustomerName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户名称',
  `CustStoreId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '门店Id',
  `CustStoreName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '门店名称',
  `CustStoreCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '门店Code',
  `PreCustStoreId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户接口下单门店Id',
  `PreCustStoreName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户接口下单门店名称',
  `CustSettleId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '结算单位Id',
  `CustSettleName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '结算单位名称',
  `IsCustomer` tinyint(1) NOT NULL COMMENT '是否为客户(0否1是)',
  `CustCoopType` smallint(6) DEFAULT NULL COMMENT '客户是否有合作商品(1中瑞2非中瑞3中瑞+非中瑞)',
  `ProCode` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '省份Code',
  `ProName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '省份名称',
  `CityCode` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '城市Code',
  `CityName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '城市名称',
  `AreaCode` varchar(20) DEFAULT NULL COMMENT '区域Code',
  `AreaName` varchar(50) DEFAULT NULL COMMENT '区域名称',
  `InstallAddress` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '加装地址',
  `InstallTime` datetime DEFAULT NULL COMMENT '加装时间',
  `RequiredTime` datetime DEFAULT NULL COMMENT '要求时间',
  `LinkMan` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '联系人姓名',
  `LinkTel` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '联系电话',
  `SecondLinkTel` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '第二联系电话',
  `SecondLinkMan` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '第二联系人',
  `WarehouseId` char(12) DEFAULT NULL COMMENT '仓库Id(发货一级仓)',
  `WarehouseName` varchar(100) DEFAULT NULL COMMENT '仓库名称(发货一级仓)',
  `Remark` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户备注',
  `IsUrgent` tinyint(1) NOT NULL DEFAULT '0' COMMENT '检修工单是否紧急(0否1是)',
  `CustUniqueSign` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户唯一标识',
  `CreatePersonCode` varchar(50) DEFAULT NULL COMMENT '用户登录名(建单人Code)',
  `CreatePersonName` varchar(50) DEFAULT NULL COMMENT '用户姓名(建单人姓名)',
  `EffectiveTime` datetime DEFAULT NULL COMMENT '工单生效时间',
  `EffectiveSuccessfulTime` datetime DEFAULT NULL COMMENT '下单成功生效时间',
  `CloseAt` datetime DEFAULT NULL COMMENT '关闭时间',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime DEFAULT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `LastUpdateTimeStamp` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近更新时间',
  PRIMARY KEY (`Id`),
  KEY `NON-AppCode` (`AppCode`),
  KEY `NON-AreaCode` (`AreaCode`),
  KEY `NON-CityCode` (`CityCode`),
  KEY `NON-CreatedAt` (`CreatedAt`),
  KEY `NON-CreateType` (`CreateType`),
  KEY `NON-CustomerId` (`CustomerId`),
  KEY `NON-CustSettleId` (`CustSettleId`),
  KEY `NON-CustStoreCode` (`CustStoreCode`),
  KEY `NON-CustStoreId` (`CustStoreId`),
  KEY `NON-CustUniqueSign` (`CustUniqueSign`),
  KEY `NON-InstallTime` (`InstallTime`),
  KEY `NON-LinkMan` (`LinkMan`),
  KEY `NON-ProCode` (`ProCode`),
  KEY `NON-RequiredTime` (`RequiredTime`),
  KEY `NON-ServiceProviderCode` (`ServiceProviderCode`),
  KEY `NON-WorkOrderType` (`OrderType`),
  KEY `NON-WorkStatus` (`WorkStatus`),
  KEY `NON_LinkTel` (`LinkTel`),
  KEY `NON-LastUpdateTimeStamp` (`LastUpdateTimeStamp`),
  KEY `NON-CreatePersonCode` (`CreatePersonCode`),
  KEY `NON-CreatePersonName` (`CreatePersonName`),
  KEY `NON-Remark` (`Remark`) USING BTREE,
  KEY `NON-CloseAt` (`CloseAt` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='工单信息表';

CREATE TABLE `tb_worksubjectsummary` (
  `Id` char(12) NOT NULL COMMENT '工单科目分类主键(JS)',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `SubjectCodeSummary` varchar(50) DEFAULT NULL COMMENT '科目Code(汇总)',
  `SubjectNameSummary` varchar(100) DEFAULT NULL COMMENT '科目名称(汇总)',
  `SubjectNum` int(11) DEFAULT NULL COMMENT '科目数量',
  `InsertTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  KEY `NON-SubjectCodeSummary` (`SubjectCodeSummary`),
  KEY `NON-WorkOrderId` (`WorkOrderId`),
  KEY `NON-SubjectNameSummary` (`SubjectNameSummary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='工单服务科目汇总表';

CREATE TABLE `tb_workserviceinfo` (
  `Id` char(12) NOT NULL COMMENT '工单服务信息主键(WS)',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `ServiceType` smallint(1) DEFAULT NULL COMMENT '服务方式(4常规安装5上门安装6集中安装7道路救援)',
  `AreaType` smallint(1) DEFAULT NULL COMMENT '区域类型(1市区2县城3乡镇)',
  `Privoder` smallint(1) DEFAULT NULL COMMENT '服务方(0中瑞1客户)',
  `InstitutionCode` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '服务机构Code',
  `IsSelfService` tinyint(1) DEFAULT NULL COMMENT '工程师属性(1本人0他人)',
  `ServiceId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工程师用户Id',
  `ServiceCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工程师登陆账号',
  `ServiceName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工程师姓名',
  `WorkerId` char(36) DEFAULT NULL COMMENT '小工Id',
  `WorkerCode` varchar(50) DEFAULT NULL COMMENT '小工账号',
  `WorkerName` varchar(50) DEFAULT NULL COMMENT '小工姓名',
  `IsPreInstall` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否前加装(0否1是)',
  `CarServiceRelation` smallint(6) DEFAULT NULL COMMENT '车辆与服务是否相关(0否1是)',
  `CompleteTime` datetime DEFAULT NULL COMMENT '安装完成时间',
  `Remark` varchar(1000) DEFAULT NULL COMMENT '备注(备案)',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime DEFAULT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `LastUpdateTimeStamp` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近更新时间',
  `IsMigrateSHYF` smallint(6) DEFAULT NULL COMMENT '是否同步叁好优服：0.否；1.是；',
  PRIMARY KEY (`Id`),
  KEY `NON-AreaType` (`AreaType`),
  KEY `NON-ServiceCode` (`ServiceCode`),
  KEY `NON-ServiceType` (`ServiceType`),
  KEY `NON-WorkOrderId` (`WorkOrderId`),
  KEY `NON-Privoder` (`Privoder`),
  KEY `NON-LastUpdateTimeStamp` (`LastUpdateTimeStamp`),
  KEY `NON-InstitutionCode` (`InstitutionCode`),
  KEY `NON-WorkerCode` (`WorkerCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='工单服务信息';

CREATE TABLE `tb_custcolumn` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `TypeCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户推送特殊字段',
  `TypeName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '推送字段名翻译',
  `Value` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '推送信息',
  `InsertTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  KEY `NON-WorkOrderId` (`WorkOrderId`),
  KEY `NON-Value` (`Value`)
) ENGINE=InnoDB AUTO_INCREMENT=198585 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='客户字段推送翻译';

CREATE TABLE `tb_workcarinfo` (
  `Id` char(12) NOT NULL COMMENT '工单车辆信息主键(WC)',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `VinNumber` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车架号',
  `PlateNumber` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车牌号',
  `PlateColor` varchar(50) DEFAULT NULL COMMENT '车牌颜色Code(basic_datadictionary.code)',
  `EngineNumber` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '发动机号',
  `CarModelId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车型Id',
  `CarModelName` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车型名称',
  `CarSeriesId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车系Id',
  `CarSeriesName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车系名称',
  `CarBrandId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车辆品牌Id',
  `CarBrandName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车辆品牌名称',
  `CarFullName` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车型全称',
  `Color` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车辆颜色',
  `CarPrice` decimal(18,2) DEFAULT NULL COMMENT '车辆价格',
  `IsNewCar` smallint(6) DEFAULT NULL COMMENT '车辆类型(0二手车1新车)',
  `CarType` smallint(6) DEFAULT NULL COMMENT '车辆类型(1新车2二手车)',
  `UserName` varchar(50) DEFAULT NULL COMMENT '用户姓名(车主)',
  `UserTel` varchar(50) DEFAULT NULL COMMENT '联系方式(车主)',
  `UserCityCode` varchar(10) DEFAULT NULL COMMENT '城市Code(车主所在)',
  `UserCityName` varchar(50) DEFAULT NULL COMMENT '城市名称(车主所在)',
  `UserAddress` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '车主地址',
  `Remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `ShortVin` varchar(10) DEFAULT NULL COMMENT '车架号(后6位)',
  `ShortFourVin` varchar(10) DEFAULT NULL COMMENT '车架号(后4位)',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `LastUpdateTimeStamp` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近更新时间',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UNI-WorkOrderId` (`WorkOrderId`),
  KEY `NON-PlateNumber` (`PlateNumber`),
  KEY `NON-ShortFourVin` (`ShortFourVin`),
  KEY `NON-ShortVin` (`ShortVin`),
  KEY `NON-UserName` (`UserName`),
  KEY `NON-VinNumber` (`VinNumber`),
  KEY `NON-LastUpdateTimeStamp` (`LastUpdateTimeStamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='车主车辆信息表';

CREATE TABLE `tb_feeiteminfo` (
  `Id` char(12) NOT NULL COMMENT '费用配置项主键(II)',
  `FeeTypeCode` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '费用类型Code（basic_datadictionary.Code)',
  `OrgCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '组织编码（1001车电 1002金融 1003车务 1000平台）',
  `FeeItemName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '费用项目Name',
  `Enable` smallint(6) DEFAULT NULL COMMENT '是否启用（1开启 0关闭）',
  `Remark` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '费用说明',
  `GenerationMode` varchar(10) DEFAULT NULL COMMENT '生成方式',
  `DistributionMode` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '发放方式（001按单发放）',
  `SortOrder` bigint(20) DEFAULT NULL COMMENT '排序字段',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime DEFAULT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-Enable` (`Enable`),
  KEY `NON-FeeItemName` (`FeeItemName`),
  KEY `NON-FeeTypeCode` (`FeeTypeCode`),
  KEY `NON-OrgCode` (`OrgCode`),
  KEY `NON-SortOrder` (`SortOrder`),
  KEY `GenerationMode` (`GenerationMode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='通用域_费用项配置表';

CREATE TABLE `rp_workordercount` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `WorkOrderId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工单Id',
  `SubjectClassCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '科目分类',
  `ServiceSubjectCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '服务科目编号',
  `ServiceSubjectName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '服务科目名称',
  `PricingMethodCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '计价方式编号',
  `PricingMethodName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '计价方式名称',
  `WorkClassCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工单分类编号',
  `WorkClassName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工单分类名称',
  `InternalPrice` decimal(10,2) DEFAULT NULL COMMENT '内部结算价格',
  `GeneralGoodsNames` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '常规商品名称',
  `ArtificialServiceGoodsId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '人工服务产品Id',
  `ArtificialServicePriceId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '人工服务商品Id',
  `ArtificialServicePriceName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '人工服务商品名称',
  `ArtificialServicePrice` decimal(10,2) DEFAULT NULL COMMENT '人工服务商品价格',
  `ArtificialServicePriceAmount` int(8) NOT NULL COMMENT '人工服务商品数量',
  `DeviceAmount` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '设备数',
  `CompleteTime` datetime DEFAULT NULL COMMENT '施工完成时间',
  `IsSelfService` tinyint(1) DEFAULT NULL COMMENT '施工人属性(1本人0他人)',
  `ServiceCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '施工人登陆账号',
  `ServiceName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '施工人姓名',
  `ServiceAscription` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '施工人归属',
  `RecordCode` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备案人(账号)',
  `RecordName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备案人(姓名)',
  `RecordAscription` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备案人归属',
  `TagSign` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0正常 1锁定价格',
  `InsertTime` datetime NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `ServiceDepartId` char(36) DEFAULT NULL COMMENT '施工人部门Id',
  `ServiceDepartName` varchar(100) DEFAULT NULL COMMENT '施工人部门名称',
  PRIMARY KEY (`Id`),
  KEY `NON-InsertTime` (`InsertTime`),
  KEY `NON-ArtificialServicePriceName` (`ArtificialServicePriceName`),
  KEY `NON-WorkOrderId` (`WorkOrderId`)
) ENGINE=InnoDB AUTO_INCREMENT=11929 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='工单计价表';

